version: '3.8'

services:
  # Development API service
  api-dev:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - DATABASE_URL=sqlite+aiosqlite:///./dev.db
      - REDIS_URL=redis://redis:6379/0
      - API_KEYS=dev-key-123,test-key-456
      - UPLOAD_MAX_SIZE=104857600
      - CORS_ORIGINS=["*"]
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    depends_on:
      - redis
    restart: unless-stopped
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Redis for development
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Redis Commander for development
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

networks:
  default:
    name: video_composition_dev_network
